name: release-maven-central

on:
  workflow_dispatch:
    inputs:
      version_scale:
        description: "Version scale"
        required: true
        default: "patch"
jobs:
  publish:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure CI Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Configure Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: >-
            [
              {
                "id": "ossrh",
                "username": "${{ secrets.SIDEKICK_SONATYPE_NEXUS_USERNAME}}",
                "password": "${{ secrets.SIDEKICK_SONATYPE_NEXUS_PASSWORD}}"
              }
            ]
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SIDEKICK_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SIDEKICK_GPG_PASSPHRASE}}
      - name: Increase Minor Version
        if: ${{ github.event.inputs.version_scale == 'minor' }}
        run: mvn -f sidekick build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT versions:commit
        working-directory: sidekick
      - name: Increase Major Version
        if: ${{ github.event.inputs.version_scale == 'major' }}
        run: mvn -f sidekick build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0-SNAPSHOT versions:commit
        working-directory: sidekick
      - name: Build and Release with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
        run: mvn clean package release:clean release:prepare release:perform release:clean --batch-mode -P release
        working-directory: sidekick